name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    # Check whether "run build" is successful
    - run: npm run build
